version: "3.7"
services:
  template:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8096:8096"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
#   command: ["redis-server", "--appendonly", "yes"]
#    volumes:
#      - redis-data:/data

